#!/bin/bash

if [ ! -d "/var/lib/mysql/${DATABASE_NAME}" ]; then
	
	mysqld --bootstrap << EOF
			FLUSH PRIVILEGES;

			ALTER USER 'root'@'localhost' IDENTIFIED BY '${DATABASE_ROOT_PASSWORD}';
			CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};
			CREATE USER '${DATABASE_USER}'@'%' IDENTIFIED by '${DATABASE_USER_PASSWORD}';
			GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'%';
		
			FLUSH PRIVILEGES;
EOF
fi

exec $@